version: '2'

services:
  app:
    image: 'store:latest'
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/store
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    networks:
      - mynet

  db:
    image: postgres:16.2
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=store
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always
    command: postgres -c wal_level=logical
    networks:
      - mynet

volumes:
  postgres:

networks:
  mynet:
    driver: bridge