spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/store
    username: admin
    password: admin
  jpa:
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        format_sql: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        javax:
          cache:
            missing_cache_strategy: create
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml